name: Run Discord Bot

on:
  schedule:
    - cron: '0 */5 * * *' # Her 5 saatte bir işi otomatik yeniler
  workflow_dispatch: # Elle başlatma butonunu etkinleştirir

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Repo Kodlarını Çek
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Sistem Paketlerini Yükle (FFmpeg)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Python Kütüphanelerini Kur
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Botu Başlat
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: python main.py
